name: instagramhome
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.0.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  dependencies:
  font_awesome_flutter: ^9.1.0
  environment:
  sdk: ">=2.12.0 <3.0.6"

flutter:
  uses-material-design: true
