name: flutter_application_1
description: A new Flutter project.
publish_to: "none" # If you do not intend to publish this project, this is fine.
version: 0.1.0

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.5 # Only declare this once

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
